# Site settings
title: Canor의 이야
tagline: Canor이 적어가는 삶의 이야기
email: helios7157@gmail.com
description: > # this means to ignore newlines until "baseurl"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://canorus.github.io" # the base hostname & protocol for your site
twitter_username: psCanor
github_username:  canorus
paginate: 5

# Build settings
markdown: redcarpet
highlighter: pygments

# Gems
gems: [jekyll-paginate]