# Site settings
title: Fabulam Canor
email: helios7157@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://canorus.github.io" # the base hostname & protocol for your site
twitter_username: psCanor
github_username:  canorus
paginate: 5

# Build settings
markdown: redcarpet
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
highlighter: pygments
permalink: pretty
safe: true
lsi: true
gems: [jekyll-paginate]