# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Fabulam Canor
tagline:          story of Canor
description:
url:              http://canorus.github.io
baseurl:          http://canorus.github.io/

author:
  name:           'Canor Eom'
  url:            https://twitter.com/psCanor

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/karloespiritu/blackdoc
